#!/bin/python3

import math
import os
import random
import re
import sys
sys.setrecursionlimit(10**8)
#
# Complete the 'journeyToMoon' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. 2D_INTEGER_ARRAY astronaut
#

def journeyToMoon(n, astronaut):
    # Write your code here
    graph = [[] for _ in range(n)]
    visited = [False] * n
    
    for i,j in astronaut:
        graph[i].append(j)
        graph[j].append(i)
        
    total_pairs = (n * (n-1)) // 2
    
    def dfs(u , visited , graph):
        visited[u] = True
        vertices = 1
        for v in graph[u]:
            if visited[v] is False:
                vertices += dfs(v , visited , graph)
        return vertices
        
    for node in range(n):
        if visited[node] is False:
            same_country_people = dfs(node , visited , graph)
            total_pairs -= (same_country_people * (same_country_people-1)) // 2
    return total_pairs

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    p = int(first_multiple_input[1])

    astronaut = []

    for _ in range(p):
        astronaut.append(list(map(int, input().rstrip().split())))

    result = journeyToMoon(n, astronaut)

    fptr.write(str(result) + '\n')

    fptr.close()
